[package]
name = "linked_devices_types"
version = "0.1.0"
edition = "2021"

[dependencies]
hdi = { workspace = true }
serde = { workspace = true }
holochain_serialized_bytes = { workspace = true }

[dev-dependencies]
fixt = "0.5"
hdi = { workspace = true, features = [ "test_utils"] }
